exclude: |
    (?x)(
        backend/tests/|
        docs/|
        tasks.py|
        scripts/|
        version.py
    )
repos:
  - repo: https://github.com/astral-sh/ruff-pre-commit
    # Ruff version.
    rev: v0.8.3
    hooks:
      # Run the linter.
      - id: ruff
        args:
          - --fix
          - --ignore=F401,F403,E203,E402
          - --line-length=99
      # Run the formatter.
      - id: ruff-format

  - repo: local
    hooks:

      - id: mypy
        name: mypy
        entry: |
          mypy
          --ignore-missing-imports
          --install-types
          --non-interactive
          --strict
          --implicit-reexport
          --warn-unused-ignores
          --cache-fine-grained
          --no-namespace-packages
        files: \.py$
        exclude: tasks.py
        language: python


      - id: pylint
        name: Pylint
        entry: pylint
        files: \.py$
        exclude: tasks.py
        language: python
