version: '3.3'

# we use env vars values from host.
x-proxies: &proxies
  no_proxy:
  http_proxy:
  https_proxy:
  NO_PROXY:
  HTTP_PROXY:
  HTTPS_PROXY:

services:

  postgres:
    volumes:
      - ./sql:/sql/:ro
    env_file:
      - env/dev-postgres.env

  pgadmin:
    env_file:
      - env/dev-pgadmin.env

  celeryworker:
    build:
      args:
        env: dev
    volumes:
      - ./backend/app:/app/:ro
    env_file:
      - env/dev-celeryworker.env
      - env/dev-postgres.env
      - env/dev-backend.env

  backend:
    build:
      args:
        env: dev
    volumes:
      - ./backend:/backend/:rw
    env_file:
      - env/dev-celeryworker.env
      - env/dev-postgres.env
      - env/dev-backend.env
    ports:
      - "80:80"

  tests:
    build:
      context: ./
      dockerfile: docker/tests/Dockerfile
      args:
        env: dev
        <<: *proxies
    volumes:
      - ./backend:/backend/:ro
    env_file:
      - env/dev-celeryworker.env
      - env/dev-postgres.env
      - env/dev-backend.env
    depends_on:
      - redis
      - backend
